spring:
  main:
    allow-circular-references: true
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
cloud:
  aws:
    s3:
      bucket: local-embedded-bucket
      mock:
        port: 5050
    region:
      static: ap-northeast-2
    stack:
      auto: false

